import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} h-screen`}>
                <div>
                    <Header />
                    <div className="lg:w-[75%] mx-auto">{children}</div>
                    <div className="pt-14 fixed top-0 right-0 lg:h-full w-full lg:w-[15%] xl:w-[10%] hidden lg:block border-l-2">
                        <div className="bg-orange p-5 lg:min-h-28 xl:min-h-36 text-white text-center flex justify-center items-center">
                            Never lose your data by signing in to your account!
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
